DevTestProject/DevTestProject/Controllers/WorkItemsController.cs
using DevTestProject.Models;
using DevTestProject.Services.Classes;
using DevTestProject.ViewModel;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DevTestProject.Controllers
{
    public class WorkItemsController : Controller
    {
        private readonly WorkItemsService _workItemService = new WorkItemsService();
        private readonly ProjectsService _projectService = new ProjectsService();
        private readonly EmployeesService _employeesService = new EmployeesService();
        // GET: WorkItems
        public ActionResult Index()
        {
            string errorMsg = String.Empty;
            if (TempData.ContainsKey("error"))
            {
                errorMsg = TempData["error"].ToString();
            }
            List<WorkItemsModel> workItems = new List<WorkItemsModel>();
            try
            {
                workItems = _workItemService.GetAllWorkItems();
            }
            catch (Exception e)
            {
                TempData["error"] = $"Problems with getting information from database (services). {e.Message}";
                return RedirectToAction("Index", "Home");
            }
            WorkItemsVm model = new WorkItemsVm()
            {
                 WorkItems = workItems,
                 ErrorMsg = errorMsg
            };
            return View("Index", model);
        }


        public ActionResult Create()
        {
            string errorMsg = String.Empty;
            if (TempData.ContainsKey("error"))
            {
                errorMsg = TempData["error"].ToString();
            }
            List<SelectListItem> projectsList = new List<SelectListItem>();
            List<SelectListItem> employeeList = new List<SelectListItem>();
            try
            {
                projectsList = Utils.Helper.GetProjectsList();

            }
            catch (Exception e)
            {

                TempData["error"] = $"Problems with getting information from database (services). {e.Message}";
                return RedirectToAction("Index", "Home");
            }           

            if(TempData.ContainsKey("error"))
            {
                errorMsg = TempData["error"].ToString();
            }
            WorkItemsVm model = new WorkItemsVm()
            {
                ProjectsList = projectsList,
                EmployeeList = employeeList,
                ErrorMsg = errorMsg
            };
            

            return View("Create", model);
        }

        [HttpPost]
        public ActionResult Create(WorkItemsVm model)
        {
            
            if (model is null)
            {
                return RedirectToAction("Create");
            }
            if (String.IsNullOrWhiteSpace(model.Name) ||
                model.Project_Id == null || model.Project_Id == 0 ||
                model.Employee_Id == null || model.Employee_Id == 0 ||
                model.DateCreated == DateTime.MinValue || 
                (model.DateCreated == DateTime.MinValue && model.DateDue == DateTime.MinValue) || 
                model.DateCreated == DateTime.MinValue || model.DateDue == DateTime.MinValue || 
                DateTime.Compare(model.DateCreated, model.DateDue) > 0)
            {
                TempData["error"] = "You did not enter information correctly. Check the information and try again.";
                return RedirectToAction("Create");
            }

            if (model.DateStarted != null && model.DateFinished != null)
            {
                if (model.DateStarted.Value != DateTime.MinValue && model.DateFinished.Value != DateTime.MinValue)
                {
                    if (DateTime.Compare(model.DateStarted.Value, model.DateFinished.Value) > 0)
                    {
                        TempData["error"] = "You did not enter dates correctly. Check the dates and try again.";
                        return RedirectToAction("Create");
                    }
                }
            }
            WorkItemsModel workItem = new WorkItemsModel()
            {
                Name = model.Name,
                Description = model.Description,
                Project_Id = model.Project_Id,
                Employee_Id = model.Employee_Id,
                DateCreated = model.DateCreated,
                DateStarted = model.DateStarted,
                DateFinished = model.DateFinished,
                DateDue = model.DateDue
            };
            try
            {
                if(!_workItemService.Create(workItem))
                {
                    TempData["error"] = $"Problems with create work item (Service error \"Create\").";
                    return RedirectToAction("Create");
                }
            }
            catch (Exception e)
            {
                TempData["error"] = $"Problems with saving information to database (services). {e.Message}";
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int workItem_id)
        {
            string errorMsg = String.Empty;
            if (TempData.ContainsKey("error"))
            {
                errorMsg = TempData["error"].ToString();
            }
            WorkItemsModel workItem = new WorkItemsModel();
            List<SelectListItem> projectsList = new List<SelectListItem>();
            List<SelectListItem> employeeList = new List<SelectListItem>();
            try
            {
                projectsList = Utils.Helper.GetProjectsList();
                employeeList = Utils.Helper.GetEmployeeList();
                workItem = _workItemService.GetWorkItem(workItem_id);
            }
            catch (Exception e)
            {

                TempData["error"] = $"Problems with getting information from database (services). {e.Message}";
                return RedirectToAction("Index", "Home");
            }


            WorkItemsVm model = new WorkItemsVm()
            {
                Id = workItem.Id,
                Name = workItem.Name,
                Description = workItem.Description,
                Project_Id = workItem.Project_Id,
                Employee_Id = workItem.Employee_Id,
                DateCreated = workItem.DateCreated,
                DateStarted = workItem.DateStarted,
                DateFinished = workItem.DateFinished,
                DateDue = workItem.DateDue,
                ProjectsList = projectsList,
                EmployeeList = employeeList,
                ErrorMsg = errorMsg
            };
            return View("Edit", model);
        }
        
        public ActionResult SaveEditingWorkItem(WorkItemsVm model)
        {
            if (model is null)
            {
                return RedirectToAction("Edit", new { workItem_id  = model.Id} );
            }
            if (String.IsNullOrWhiteSpace(model.Name) ||
                model.Project_Id == null || model.Project_Id == 0 ||
                model.Employee_Id == null || model.Employee_Id == 0 ||
                model.DateCreated == DateTime.MinValue ||
                (model.DateCreated == DateTime.MinValue && model.DateDue == DateTime.MinValue) ||
                model.DateDue == DateTime.MinValue || DateTime.Compare(model.DateCreated, model.DateDue) > 0)
            {
                TempData["error"] = "You did not enter information correctly. Check the information and try again.";
                return RedirectToAction("Edit", new { workItem_id = model.Id });
            }


            WorkItemsVm workItem = new WorkItemsVm()
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Project_Id = model.Project_Id,
                Employee_Id = model.Employee_Id,
                DateCreated = model.DateCreated,
                DateStarted = model.DateStarted,
                DateFinished = model.DateFinished,
                DateDue = model.DateDue
        };

            try
            {
                if(!_workItemService.Update(workItem))
                {
                    TempData["error"] = $"Problems with updating work item (Service error \"Update/Edit\").";
                    return RedirectToAction("Edit", new { workItem_id = model.Id });
                }
            }
            catch (Exception e)
            {
                TempData["error"] = $"Problems with getting information from database (services). {e.Message}";
                return RedirectToAction("Edit", new { workItem_id = model.Id });
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int workItem_id)
        {
            try
            {
                if(!_workItemService.Delete(workItem_id))
                {
                    TempData["error"] = $"Problems with deleting work item (Service error \"Delete\").";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["error"] = $"Problems with getting information from database (services) or deleting information. {e.Message}";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Method for getting all employees who are working on project via AJAX
        /// </summary>
        /// <param name="project_id"></param>
        /// <returns></returns>
        public ActionResult GetEmployeesFromProject(string project_id)
        {
            if(string.IsNullOrWhiteSpace(project_id))
            {
                return Json( new { success = false}); 
            }
            int projectId = int.Parse(project_id);
            List<int> employeesId = _workItemService.GetAllEmployeeFromProject(projectId);
            return Json(new { empId = employeesId });
        }

    }
}

DevTestProject/DevTestProject/Views/WorkItems/Create.cshtml
@model DevTestProject.ViewModel.WorkItemsVm

@if (!String.IsNullOrEmpty(Model.ErrorMsg))
{
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @Model.ErrorMsg;
    </div>
}
<div class="row">

    @using (Html.BeginForm("Create", "WorkItems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {

        @Html.HiddenFor(m => m.Id)
        @Html.AntiForgeryToken()
        <h2>Create work item</h2>
        <hr />
        @Html.ValidationSummary()
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Project_Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10" id="">
                @Html.DropDownListFor(model => model.Project_Id, Model.ProjectsList, new { @class = "form-control", @placeholder = "Set project", id = "projectList" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Employee_Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Employee_Id, Model.EmployeeList, new { @class = "form-control", @placeholder = "Set employee", id = "employeeList" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateCreated, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateCreated, new { @class = "form-control", type = "date" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateStarted, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateStarted, new { @class = "form-control", type = "date" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.DateFinished, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateFinished, new { @class = "form-control", type = "date" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateDue, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateDue, new { @class = "form-control", type = "date" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" class="btn btn-success" value="Create" />
                <input class="btn btn-primary" type="button" value="Cancel" onclick="location.href='@Url.Action("Index")';" />
            </div>

        </div>
    }

</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/WorkItemAjaxRequest");

DevTestProject/DevTestProject/Views/WorkItems/Edit.cshtml
@model DevTestProject.ViewModel.WorkItemsVm
@if (!String.IsNullOrEmpty(Model.ErrorMsg))
{
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @Model.ErrorMsg;
    </div>
}

<div class="row">

    @using (Html.BeginForm("SaveEditingWorkItem", "WorkItems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.HiddenFor(m => m.Id)
        @Html.AntiForgeryToken()
        <h2>Work item editing</h2>
        <hr />
        @Html.ValidationSummary()
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Project_Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10" id="">
                @Html.DropDownListFor(model => model.Project_Id, Model.ProjectsList, new { @class = "form-control", @placeholder = "Set project", id = "projectList" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Employee_Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Employee_Id, Model.EmployeeList, new { @class = "form-control", @placeholder = "Set employee", id = "employeeList" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateCreated, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateCreated, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateStarted, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateStarted, new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.DateFinished, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateFinished, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateDue, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateDue, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" class="btn btn-success" value="Save" />
                <input class="btn btn-primary" type="button" value="Cancel" onclick="location.href='@Url.Action("Index")';" />
            </div>

        </div>
    }

</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/WorkItemAjaxRequest");

DevTestProject/DevTestProject/Views/WorkItems/Index.cshtml
@model DevTestProject.ViewModel.WorkItemsVm
    <h2>Work items</h2>
    <div class="row">
        <div class="col-md-2">
            <input class="btn btn-success" type="button" value="Create work item" onclick="location.href='@Url.Action("Create", "WorkItems")';" />
        </div>
    </div>

    <div class="row">
        @if (!String.IsNullOrEmpty(Model.ErrorMsg))
        {
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                @Model.ErrorMsg;
            </div>
        }
        <div class="col-md-12">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Project_Id</th>
                        <th scope="col">Employee_Id</th>
                        <th scope="col">DateCreated</th>
                        <th scope="col">DateStarted</th>
                        <th scope="col">DateFinished</th>
                        <th scope="col">DateDue</th>
                        <th scope="col" colspan="2">Work item settings</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var workItem in Model.WorkItems)
                    {
                        <tr>
                            <th scope="row">@workItem.Id</th>
                            <td>@workItem.Name</td>
                            <td>@workItem.Description</td>
                            <td>@workItem.Project_Id</td>
                            <td>@workItem.Employee_Id</td>
                            <td>@workItem.DateCreated</td>
                            <td>@workItem.DateStarted</td>
                            <td>@workItem.DateFinished</td>
                            <td>@workItem.DateDue</td>
                            <td>
                                <input class="btn btn-info" type="button" value="Edit" onclick="location.href='@Url.Action("Edit", new { workItem_id = workItem.Id})';" />
                            </td>
                            <td>
                                <input class="btn btn-danger" type="button" value="Delete" onclick="location.href='@Url.Action("Delete", new { workItem_id = workItem.Id})';" />
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>


    </div>