DevTestProject/DevTestProject/Controllers/ProjectCooperationsController.cs
using DevTestProject.Models;
using DevTestProject.Services.Classes;
using DevTestProject.ViewModel;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DevTestProject.Controllers
{
    public class ProjectCooperationsController : Controller
    {
        private readonly ProjectCooperationService _projectCooperaionsService = new ProjectCooperationService();
        private readonly ProjectsService _projectService = new ProjectsService();
        private readonly TeamsService _teamsService = new TeamsService();
        // GET: ProjectCooperations
        public ActionResult Index()
        {
            string errorMsg = String.Empty;
            if (TempData.ContainsKey("error"))
            {
                errorMsg = TempData["error"].ToString();
            }
            List<ProjectCooperaionsModel> projectCooperations = new List<ProjectCooperaionsModel>();
            List<ProjectsModel> allProjects = new List<ProjectsModel>();
            List<TeamsModel> allTeams = new List<TeamsModel>();

            try
            {
                projectCooperations = _projectCooperaionsService.GetAllCooperations();
                allProjects = _projectService.GetAllProjects();
                allTeams = _teamsService.GetTeams();

            }
            catch (Exception e)
            {
                TempData["error"] = $"Problems with getting information from database (services). {e.Message}";
                return RedirectToAction("Index", "Home");
            }
            ProjectCooperationsVm model = new ProjectCooperationsVm()
            {
                ProjectCooperations = projectCooperations,
                AllProjects = allProjects,
                AllTeams = allTeams,
                ErrorMsg = errorMsg

            };
            return View("Index", model);
        }


        public ActionResult Create()
        {
            string errorMsg = String.Empty;
            if (TempData.ContainsKey("error"))
            {
                errorMsg = TempData["error"].ToString();
            }
            List<SelectListItem> projectList = new List<SelectListItem>();
            List<SelectListItem> teamList = new List<SelectListItem>();
            try
            {
                projectList = Utils.Helper.GetProjectsList();
                teamList = Utils.Helper.GetTeamList();
            }
            catch (Exception e)
            {

                TempData["error"] = $"Problems with getting information from database (services). {e.Message}";
                return RedirectToAction("Index", "Home");
            }

            ProjectCooperationsVm model = new ProjectCooperationsVm()
            {
                ProjectList = projectList,
                TeamList = teamList,
                ErrorMsg = errorMsg
            };
            return View("Create", model);
        }
        [HttpPost]
        public ActionResult Create(ProjectCooperationsVm model)
        {
            if (model is null || model.DateAssigned == DateTime.MinValue || model.Project_Id == 0 || model.Project_Id == null || model.Team_Id == 0 || model.Team_Id == null)
            {
                TempData["error"] = $"All data must be filled";
                return RedirectToAction("Create");
            }

            ProjectCooperaionsModel projectCooperations = new ProjectCooperaionsModel()
            {
                Project_Id = model.Project_Id,
                Team_Id = model.Team_Id,
                DateAssigned = model.DateAssigned,
            };
            try
            {
                
                if(!_projectCooperaionsService.CheckIfRecordExist(projectCooperations))
                {
                    if(!_projectCooperaionsService.Create(projectCooperations))
                    {
                        TempData["error"] = $"Problems with create project cooperation (Service error \"Create\").";
                        return RedirectToAction("Create");
                    }
                } 
                else
                {
                    TempData["error"] = $"This combination already exists. You are trying to duplicate (Service error \"Create\").";
                    return RedirectToAction("Create");
                }
                
                
            }
            catch (Exception e)
            {

                TempData["error"] = $"Problems with saving information to database (services). {e.Message}";
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index");
        }



        public ActionResult Edit(int projectCooperations_id)
        {
            string errorMsg = String.Empty;
            if (TempData.ContainsKey("error"))
            {
                errorMsg = TempData["error"].ToString();
            }
            ProjectCooperaionsModel projectCooperations = new ProjectCooperaionsModel();
            List<SelectListItem> projectList = new List<SelectListItem>();
            List<SelectListItem> teamList = new List<SelectListItem>();
            try
            {
                projectList = Utils.Helper.GetProjectsList();
                teamList = Utils.Helper.GetTeamList();
                projectCooperations = _projectCooperaionsService.GetProjectCooperation(projectCooperations_id);
            }
            catch (Exception e)
            {

                TempData["error"] = $"Problems with getting information from database (services). {e.Message}";
                return RedirectToAction("Index", "Home");
            }


            ProjectCooperationsVm model = new ProjectCooperationsVm()
            {
                ProjectList = projectList,
                TeamList = teamList,
                Id = projectCooperations.Id,
                Project_Id = projectCooperations.Project_Id,
                Team_Id = projectCooperations.Team_Id,
                DateAssigned = projectCooperations.DateAssigned,
                ErrorMsg = errorMsg
            };


            return View("Edit", model);
        }

        public ActionResult SaveEdititngProjectCooperations(ProjectCooperationsVm model)
        {

            if (model is null || model.DateAssigned == DateTime.MinValue || model.Project_Id == 0 || model.Project_Id == null || model.Team_Id == 0 || model.Team_Id == null)
            {
                TempData["error"] = $"Problems with saving information to database (services).";
                return RedirectToAction("Edit", new { projectCooperations_id = model.Id });
            }
            ProjectCooperaionsModel projectCooperations = new ProjectCooperaionsModel()
            {
                Id = model.Id,
                Project_Id = model.Project_Id,
                Team_Id = model.Team_Id,
                DateAssigned = model.DateAssigned
            };

            try
            {
                if(!_projectCooperaionsService.Update(projectCooperations))
                {
                    TempData["error"] = $"Problems with updating project cooperation (Service error \"Update/Edit\").";
                    return RedirectToAction("Edit", new { projectCooperations_id = model.Id });
                }
            }
            catch (Exception e)
            {
                TempData["error"] = $"Problems with getting information from database (services). {e.Message}";
                return RedirectToAction("Edit", new { projectCooperations_id = model.Id });
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int projectCooperations_id)
        {
            try
            {
                if(!_projectCooperaionsService.Delete(projectCooperations_id))
                {
                    TempData["error"] = $"Problems with deleting project cooperation (Service error \"Delete\").";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["error"] = $"Problems with getting information from database (services) or deleting information. {e.Message}";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

DevTestProject/DevTestProject/Views/ProjectCooperations/Create.cshtml
@model DevTestProject.ViewModel.ProjectCooperationsVm

@if (!String.IsNullOrEmpty(Model.ErrorMsg))
{
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @Model.ErrorMsg;
    </div>
}
<div class="row">

    @using (Html.BeginForm("Create", "ProjectCooperations", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.HiddenFor(m => m.Id)
        @Html.AntiForgeryToken()
        <h4>Create project cooperations</h4>
        <hr />
        @Html.ValidationSummary()


        <div class="form-group">
            @Html.LabelFor(m => m.Project_Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Project_Id, Model.ProjectList, new { @class = "form-control", @placeholder = "Set team" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Team_Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Team_Id, Model.TeamList, new { @class = "form-control", @placeholder = "Set team" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.DateAssigned, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateAssigned, new { @class = "form-control", type = "date" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" class="btn btn-success" value="Create" />
                <input class="btn btn-primary" type="button" value="Cancel" onclick="location.href='@Url.Action("Index")';" />
            </div>

        </div>
    }

</div>

DevTestProject/DevTestProject/Views/ProjectCooperations/Edit.cshtml
@model DevTestProject.ViewModel.ProjectCooperationsVm
@if (!String.IsNullOrEmpty(Model.ErrorMsg))
{
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @Model.ErrorMsg;
    </div>
}

<div class="row">

    @using (Html.BeginForm("SaveEdititngProjectCooperations", "ProjectCooperations", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.HiddenFor(m => m.Id)
        @Html.AntiForgeryToken()
        <h2>Project cooperations editing</h2>
        <hr />
        @Html.ValidationSummary()

        <div class="form-group">
            @Html.LabelFor(m => m.Project_Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Project_Id, Model.ProjectList, new { @class = "form-control", @placeholder = "Set project id" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Team_Id, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Team_Id, Model.TeamList, new { @class = "form-control", @placeholder = "Set team id" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DateAssigned, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateAssigned, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" class="btn btn-success" value="Save" />
                <input class="btn btn-primary" type="button" value="Cancel" onclick="location.href='@Url.Action("Index")';" />
            </div>

        </div>
    }

</div>

DevTestProject/DevTestProject/Views/ProjectCooperations/Index.cshtml
@model DevTestProject.ViewModel.ProjectCooperationsVm
<h2>Project cooperations</h2>
<div class="row">
    <div class="col-md-2">
        <input class="btn btn-success" type="button" value="Create project cooperation" onclick="location.href='@Url.Action("Create", "ProjectCooperations")';" />
    </div>
</div>

<div class="row">
    @if (!String.IsNullOrEmpty(Model.ErrorMsg))
    {
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            @Model.ErrorMsg;
        </div>
    }
    <div class="col-md-12">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Project_Id</th>
                    <th scope="col">Project name</th>
                    <th scope="col">Team_Id</th>
                    <th scope="col">Team name</th>
                    <th scope="col">DateAssigned</th>
                    <th scope="col" colspan="2">Project cooperations settings</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var projectCooperation in Model.ProjectCooperations)
                {
                    <tr>
                        <th scope="row">@projectCooperation.Id</th>
                        <td>@projectCooperation.Project_Id</td>
                        @foreach (var project in Model.AllProjects)
                        {
                            if (project.Id == projectCooperation.Project_Id)
                            {
                                <td>@project.Name</td>
                            }
                        }
                        <td>@projectCooperation.Team_Id</td>
                        @foreach (var team in Model.AllTeams)
                        {
                            if (team.Id == projectCooperation.Team_Id)
                            {
                                <td>@team.Name</td>
                            }
                        }

                        <td>@projectCooperation.DateAssigned</td>
                        <td>
                            <input class="btn btn-info" type="button" value="Edit" onclick="location.href='@Url.Action("Edit", new { projectCooperations_id = projectCooperation.Id})';" />
                        </td>
                        <td>
                            <input class="btn btn-danger" type="button" value="Delete" onclick="location.href='@Url.Action("Delete", new { projectCooperations_id = projectCooperation.Id})';" />
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>


</div>